import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Playfair_Display_SC } from "next/font/google";
import "@/app/ui/globals.css";

export const playfair_display_sc = Playfair_Display_SC({subsets: ['latin'], weight:['400']});
export const playfair_display = Playfair_Display({subsets: ['latin'], weight:['500']});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Katie G Website",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
